// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMRgQD32SC5AbteqcxwXn9R-x14FvgXM',
    appId: '1:296766935842:web:2095ccca7b13bc97688b7b',
    messagingSenderId: '296766935842',
    projectId: 'tumercado-62ccd',
    authDomain: 'tumercado-62ccd.firebaseapp.com',
    storageBucket: 'tumercado-62ccd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIecAQX0A5tSCwOVZ0fZZiailevqtM0rY',
    appId: '1:296766935842:android:c5a9d17be8c04aa8688b7b',
    messagingSenderId: '296766935842',
    projectId: 'tumercado-62ccd',
    storageBucket: 'tumercado-62ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5KkTNH_1KQyjeF2ZwPYsWTbCo9dxsaY',
    appId: '1:296766935842:ios:8f8dc5aee855f5e3688b7b',
    messagingSenderId: '296766935842',
    projectId: 'tumercado-62ccd',
    storageBucket: 'tumercado-62ccd.firebasestorage.app',
    iosBundleId: 'com.example.tuMercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5KkTNH_1KQyjeF2ZwPYsWTbCo9dxsaY',
    appId: '1:296766935842:ios:8f8dc5aee855f5e3688b7b',
    messagingSenderId: '296766935842',
    projectId: 'tumercado-62ccd',
    storageBucket: 'tumercado-62ccd.firebasestorage.app',
    iosBundleId: 'com.example.tuMercado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKMRgQD32SC5AbteqcxwXn9R-x14FvgXM',
    appId: '1:296766935842:web:7c68bdf637bb7b9d688b7b',
    messagingSenderId: '296766935842',
    projectId: 'tumercado-62ccd',
    authDomain: 'tumercado-62ccd.firebaseapp.com',
    storageBucket: 'tumercado-62ccd.firebasestorage.app',
  );
}
