// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_aPJBuJ0LB71X4S61RUcSx2Fygj9S7s',
    appId: '1:340657532958:web:fc554a9dd81f6fe5e1be0f',
    messagingSenderId: '340657532958',
    projectId: 'tumercado-ecc4c',
    authDomain: 'tumercado-ecc4c.firebaseapp.com',
    storageBucket: 'tumercado-ecc4c.appspot.com',
    measurementId: 'G-W5SNLHPQYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOrsg8lkrnkjboyifWZ3t9h2ecLt9N1cE',
    appId: '1:340657532958:android:e8a2cb8f2af96515e1be0f',
    messagingSenderId: '340657532958',
    projectId: 'tumercado-ecc4c',
    storageBucket: 'tumercado-ecc4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPvwG2MjK4gJvUGsIjbAg6lD5MH8NyLA',
    appId: '1:340657532958:ios:59c8512b5752788fe1be0f',
    messagingSenderId: '340657532958',
    projectId: 'tumercado-ecc4c',
    storageBucket: 'tumercado-ecc4c.appspot.com',
    iosBundleId: 'com.example.tuMercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfPvwG2MjK4gJvUGsIjbAg6lD5MH8NyLA',
    appId: '1:340657532958:ios:59c8512b5752788fe1be0f',
    messagingSenderId: '340657532958',
    projectId: 'tumercado-ecc4c',
    storageBucket: 'tumercado-ecc4c.appspot.com',
    iosBundleId: 'com.example.tuMercado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO_aPJBuJ0LB71X4S61RUcSx2Fygj9S7s',
    appId: '1:340657532958:web:41dd5f429d4e424be1be0f',
    messagingSenderId: '340657532958',
    projectId: 'tumercado-ecc4c',
    authDomain: 'tumercado-ecc4c.firebaseapp.com',
    storageBucket: 'tumercado-ecc4c.appspot.com',
    measurementId: 'G-241QPFX9BF',
  );
}
